### ISSUE TITLE
MMC software

### ISSUE THREAD

**Issue by ArjunBangalore** [fangq/fedorapkg#2]
Hi,
I am new to use of Mesh-based Monte Carlo (MMC) for MATLAB (MMC) software. I am trying to learn. I downloaded and installed the package along with iso2mesh package, added all the folders to Matlab path. When I run any demo, the software prints 'Unrecognized function or variable 'mm''. I searched for mmc.m and could not find it. Can you help me resolve this issue? I have attached
![Message](https://user-images.githubusercontent.com/60360688/73202475-20431600-4109-11ea-8a5d-990217e2d32e.PNG)
 the message.
Thanks,
Arjun
![image](https://user-images.githubusercontent.com/60360688/73202391-f689ef00-4108-11ea-92f3-bfcb1b5927d2.png)

**Comment by sanjayankur31** [comment]
@ArjunBangalore : you are looking for this repository where MMC is developed: https://github.com/fangq/mmc

Please re-open the issue there. (This one here is to do with packaging MMC for [NeuroFedora](https://neuro.fedoraproject.org)).

**Comment by ArjunBangalore** [comment]
Thanks. Will do.
Arjun
